### ISSUE TITLE
[Bug] ERROR - u'PostPage'

### ISSUE THREAD

**Issue by msanders-lg** [althonos/InstaLooter#107]
This is the first I've encountered of this particular error, and initially I believed it to be a side-effect of the presence of a dot in a username, ex. `user.name`. But after trying another account (with multiple dots in fact), this issue seems to be isolated simply to one account. It's public, and I've tried both logged and not logged in runs. Also, it may be worth noting, when this error hits, a <kbd>Ctrl+C</kbd> doesn't cut it; I had to use <kbd>Shift+Break</kbd> to get back out.
```
msanders@instance-1:~/insta$ ./lf.sh
Loading pages | 25%(1 of 4)|###            |Elapsed Time: 0:00:04 |ETA:  0:00:1200:17:57 - ERROR - u'PostPage'
^C^\./script.sh: line 2: 16909 Quit                    (core dumped)
```
## Contents of lf.sh
```bash
#!/bin/bash
source instalooter-env/bin/activate
cd luna.freyas
./script.sh
```
## Contents of luna.freyas/script.sh
```bash
#!/bin/bash
instaLooter luna\.freyas -v -N -D -e -T {id}.{datetime}.{code}
instaLooter luna\.freyas -v -N -m -T {id}.{datetime}.{code}
```

**Comment by althonos** [comment]
I could reproduce this too, but a  <kbd>Ctrl+C</kbd> did the trick to exit. Including the traceback as a reference:
```python
Traceback (most recent call last):
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/cli.py", line 227, in main
    new_only=args['--new'],
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/core.py", line 457, in download
    new_only=new_only
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/core.py", line 534, in _fill_media_queue
    medias_queued, stop = self._add_media_to_queue(media, condition, media_count, medias_queued, new_only)
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/core.py", line 542, in _add_media_to_queue
    media, condition, media_count, medias_queued, new_only)
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/core.py", line 559, in _add_sidecars_to_queue
    media = self.get_post_info(media.get('shortcode') or media['code'])
  File "/home/althonos/.local/lib/python3.6/site-packages/instaLooter/core.py", line 507, in get_post_info
    media = self._get_shared_data(res)['entry_data']['PostPage'][0]\
KeyError: 'PostPage'
```
