### ISSUE TITLE
Credentials error: Upsetting Instagram

### ISSUE THREAD

**Issue by djvanguard** [althonos/InstaLooter#123]
For some reason this started throwing errors today, and Instagram keeps sending me warning of an unauthorized access attempt.  Looks like they changed something, unless I'm the only one getting it.  I have not changed my password recently.

Traceback (most recent call last):
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vanguard\AppData\Local\Programs\Python\Python36-32\Scripts\instaLooter.exe\__main__.py", line 9, in <module>
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\utils.py", line 174, in new_func
    result = func(*args, **kwargs)
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\cli.py", line 208, in main
    login(looter, args)
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\cli.py", line 130, in login
    looter.login(username, password)
  File "c:\users\vanguard\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\core.py", line 224, in login
    raise SystemError("Login error: check your connection")
SystemError: Login error: check your connection

**Comment by djvanguard** [comment]
Please let me know if I'm the only one encountering this issue.  I will then look into other explanations on my end.

**Comment by althonos** [comment]
@djvanguard : is this still happening ? It can occur because Instagram did not authorize connection to your computer. Can you login through the website ?

**Comment by vincentgong7** [comment]
Hi, I also met similar problem when I login with CLI, with command:

`instalooter post "https://www.instagram.com/p/BFB6znLg5s1/" ./imgs/ --username vxxx@xxxm --password xxxxxxxx`

Error:
```
instalooter.cli[23948] CRITICAL Login error: check your login data
instalooter.cli[23948] WARNING unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('157.230.31.3', 34864), raddr=('185.60.216.174', 443)>
```

I can login in via Chrome. So still do not know what is wrong with it.

BR,
Vincent

**Comment by seeker1983** [comment]
I'm having same issue. Did anyone found a solution/workaround?

**Comment by UgurGumushan** [comment]
I couldn't login either. My password is long and complex and I have to paste it. When I paste without quotes, my terminal recognizes a pipe character and it breaks the password. When I use quotes to represent a string and pass my password as a parameter, I receive the "login error: check your login data". I couldn't find a way to use this app
