### ISSUE TITLE
Can't choose which directory instaLooter saves posts when downloading batch

### ISSUE THREAD

**Issue by applepanda** [althonos/InstaLooter#125]
When I run this:
```
[Family]
get-videos = true
template = {username}.{datetime}.{id}
new = true
jobs = 24
users =
	instagram: D:\Instagram\Profiles\instagram
	therock: D:\Instagram\Profiles\therock
```

I get this error:
```
Traceback (most recent call last):
  File "c:\users\fra\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fra\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fra\AppData\Local\Programs\Python\Python36-32\Scripts\instaLooter.exe\__main__.py", line 9, in <module>

  File "c:\users\fra\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\utils.py", line 174, in new
_func
    result = func(*args, **kwargs)
  File "c:\users\fra\appdata\local\programs\python\python36-32\lib\site-packages\instaLooter\cli.py", line 180, in main
    with open(args['<batch_file>']) as batch_file:
FileNotFoundError: [Errno 2] No such file or directory: 'bat.ini'
```

If I change the directory the files are saved in to ~/Videos like the documentation shows, it works with no problem. I've tried adding quotation marks, but it doesn't work. Any help appreciated.

**Comment by althonos** [comment]
@applepanda : I attempted to patch the issue, please try latest version (`v0.13.3`).

**Comment by applepanda** [comment]
Works now, thanks
