### ISSUE TITLE
Problem when downloading images

### ISSUE THREAD

**Issue by AgoraSecurity** [althonos/InstaLooter#129]
Hello,

I'm having the following problem.
```
server@ubuntu:~$ instaLooter instagram --traceback -v 
20:48:29 - ERROR - __exit__
Traceback (most recent call last):
  File "/home/server/.local/lib/python2.7/site-packages/instaLooter/cli.py", line 227, in main
    new_only=args['--new'],
  File "/home/server/.local/lib/python2.7/site-packages/instaLooter/core.py", line 457, in download
    new_only=new_only
  File "/home/server/.local/lib/python2.7/site-packages/instaLooter/core.py", line 533, in _fill_media_queue
    for media in self.medias(media_count=media_count, with_pbar=with_pbar, timeframe=timeframe):
  File "/home/server/.local/lib/python2.7/site-packages/instaLooter/core.py", line 340, in _timeless_medias
    for page in self.pages(media_count=media_count, with_pbar=with_pbar):
  File "/home/server/.local/lib/python2.7/site-packages/instaLooter/core.py", line 275, in pages
    with self.session.get(url) as res:
AttributeError: __exit__
```

Any idea why?

Here's some debug info:
```
server@ubuntu:~$ instaLooter --version
instaLooter 0.13.3
```

**Comment by lalitmee** [comment]
Hello,

I am facing this issue while running instaLooter. Please help.

```
lalit@lalit:~/Downloads/instagram/inspirational$ instaLooter instagram --traceback -v
Traceback (most recent call last):
  File "/home/lalit/.local/bin/instaLooter", line 7, in <module>
    from instaLooter import main
ModuleNotFoundError: No module named 'instaLooter'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/lalit/.local/bin/instaLooter", line 7, in <module>
    from instaLooter import main
ModuleNotFoundError: No module named 'instaLooter'
```

**Comment by AgoraSecurity** [comment]
Hello,

I no longer need the tool. I'll close the issue.

Thanks for the answer
