### ISSUE TITLE
1.0.0 -> 2.0.0, now "CRITICAL 'ProfilePage'" "and WARNING No medias found."

### ISSUE THREAD

**Issue by JPNYC81** [althonos/InstaLooter#167]
## Library version
```
instalooter v2.0.0
```
## Environment
* Linux 4.14.16-unRAID
* Python 3.6.2

## Error description - runtime

Recently upgraded instaLooter, now when running a batch config, it fails with CRITICAL 'ProfilePage'
No idea what that means, and traceback is inconclusive. The user pages DO exist and there is media, not sure what's up. Thoughts?

```# instalooter batch /mnt/user/nextcloud/insta/instaLooter.ini```
0it [00:00, ?it/s] (this keeps getting cut out of markup)
```0it [00:00, ?it/s]2018-04-18 06:12:56 Aleph instalooter.cli[28138] WARNING No medias found.
Downloaded 0 medias !
2018-04-18 06:13:01 Aleph instalooter.cli[28138] CRITICAL 'ProfilePage'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/instalooter/cli/__init__.py", line 94, in main
    batch_runner.run_all()
  File "/usr/lib64/python3.6/site-packages/instalooter/batch.py", line 127, in run_all
    self.run_job(section_id, session=session)
  File "/usr/lib64/python3.6/site-packages/instalooter/batch.py", line 179, in run_job
    dlpbar_cls=None if quiet else TqdmProgressBar)
  File "/usr/lib64/python3.6/site-packages/instalooter/looters.py", line 435, in download
    pages_iterator = self.pages()   # type: Iterable[Dict[Text, Any]]
  File "/usr/lib64/python3.6/site-packages/instalooter/looters.py", line 708, in pages
    it = ProfileIterator.from_username(self._username, self.session)
  File "/usr/lib64/python3.6/site-packages/instalooter/pages.py", line 164, in from_username
    data = user_data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'
```

My instaLooter.ini
```[Insta]
jobs = 4
username = jpnyc81
password = p455werd
add-metadata = true
get-videos = true
dump-json = true
quiet = false
new = true
template = {username}-{date}-{id}
users =
    jpnyc81:/mnt/user/nextcloud/insta/images/jpnyc81
```

**Comment by althonos** [comment]
Fixed in `v2.0.1` hopefully (I used the same `.ini` with my own username / password and it worked).
