### ISSUE TITLE
RetryError at Runtime

### ISSUE THREAD

**Issue by ShwetanshuSingh** [althonos/InstaLooter#182]
## Library version

```
instalooter v2.0.1
```

## Environment

* *OS* - Ubuntu 12.04.2 LTS
* *Python version* - 2.7.3

## Error description - runtime

Multiple threads fail with the same error and the runtime is interrupted with about half the posts yet to be downloaded. Traceback for any one thread is as follows:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/instalooter/worker.py", line 119, in run
    self._DOWNLOAD_METHODS[media["__typename"]](media)
  File "/home/divyansha/.local/lib/python2.7/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/divyansha/.local/lib/python2.7/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/home/divyansha/.local/lib/python2.7/site-packages/tenacity/__init__.py", line 298, in iter
    six.raise_from(retry_exc, fut.exception())
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
RetryError: RetryError[<Future at 0x2846e50 state=finished raised KeyError>]
```

### Reproducible test case

```
instalooter hashtag dangerselfie Training/General --dump-json --add-metadata -T {date}-{likescount}-{ownerid}
```

### Expected behaviour

Expected the download to go through seamlessly.

### Actual behaviour

The download terminates at 736 posts specifically. This behavior was seen on multiple re-attempts as well.

**Comment by althonos** [comment]
The test I did simply had the download stop at 798 posts, but without crashing, which is strange.

But concerning the number of posts, this is because IG has a weird behaviour when it comes to hashtags: although it displays a number X of tagged posts, it will only give you Y posts when requesting metadata (with Y < X) and to "padd" the remaining posts, it will loop back to other posts it already returned. To avoid this, `instalooter` keeps track of all the tagged posts that were already seen, and stops at the first duplicate.
