### ISSUE TITLE
Error with downloading single post

### ISSUE THREAD

**Issue by Readiz** [althonos/InstaLooter#188]
Library version: 2.0.2 latest
Python 3.6 & Windows 10 x64
----

I'm woring on windows cmd console.
The traceback log is like below:

C:\Users\Readiz>instaLooter post "https://www.instagram.com/p/zzzzzzzzzzzz/" . --traceback
2018-05-25 19:17:00 Readiz-NotePC instalooter.cli[6492] NOTICE Starting download of `https://www.instagram.com/p/zzzzzzzzzzzz/`
2018-05-25 19:17:01 Readiz-NotePC instalooter.cli[6492] CRITICAL 'PostPage'
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\instalooter\cli\__init__.py", line 171, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "c:\python36\lib\site-packages\instalooter\looters.py", line 828, in download
    new_only, condition)
  File "c:\python36\lib\site-packages\instalooter\looters.py", line 600, in _fill_media_queue
    for media in six.moves.filter(_condition, medias_iter):
  File "c:\python36\lib\site-packages\instalooter\looters.py", line 792, in medias
    info = self.info
  File "c:\python36\lib\site-packages\instalooter\looters.py", line 760, in info
    self._info = self.get_post_info(self.code)
  File "c:\python36\lib\site-packages\instalooter\looters.py", line 337, in get_post_info
    return data['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'PostPage'

I'm trying with other posts, but the error message is the same.

**Comment by althonos** [comment]
You're expected to pass only the post token to the CLI, not the full URL (indeed that's a regression from pre-v1 code). Feature request is available at #184.
