### ISSUE TITLE
Fatal runtime python error

### ISSUE THREAD

**Issue by emijawdo** [althonos/InstaLooter#19]
Traceback (most recent call last):
  File "/usr/local/bin/instaLooter", line 11, in <module>
    load_entry_point('instaLooter==0.4.0', 'console_scripts', 'instaLooter')()
  File "/usr/local/lib/python3.5/dist-packages/instaLooter-0.4.0-py3.5.egg/instaLooter/__main__.py", line 58, in main
    directory=os.path.expanduser(args.get('<directory>', os.getcwd())),
  File "/usr/lib/python3.5/posixpath.py", line 229, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by althonos** [comment]
This error occured when no directory was given. An acceptance test was written. Thanks for feedback :smile:
