### ISSUE TITLE
critical error while trying to download from fresh installation

### ISSUE THREAD

**Issue by AkiselNipese** [althonos/InstaLooter#190]
Hi,

## Library version

```
instalooter 2.0.2
```

## Environment

*Describe here your environment, including:*

* *Fedora 26*
* *Python 2.7.14*

### Reproducible test case

```
pip install --user instalooter
instalooter user instagram
2018-05-26 12:25:51 new-host-2.home instalooter.cli[4070] CRITICAL "name=u'csrftoken', domain=None, path=None
```

**Comment by mratajczyk** [comment]
Looks like `csrftoken`  is no longer available in cookies. Getting it from shared data helps:

https://github.com/mratajczyk/InstaLooter/commit/4886706f31e058cc33e96c26bd18d908256668c1

**Comment by AkiselNipese** [comment]
Thanks for the answer.

I'm not sure how to apply the changes so i just edited the file myself and i got the error :

`instalooter.cli[28452] CRITICAL 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
`
I also tried to replace the whole files and got another error

```
Traceback (most recent call last):
  File "~/.local/bin/instalooter", line 7, in <module>
    from instalooter.cli import main
  File "~/.local/lib/python2.7/site-packages/instalooter/cli/__init__.py", line 27, in <module>
    from ..looters import InstaLooter, HashtagLooter, ProfileLooter, PostLooter
  File "~/.local/lib/python2.7/site-packages/instalooter/looters.py", line 25, in <module>
    from lib.InstaLooter.instalooter.proxy import get_proxy
ImportError: No module named lib.InstaLooter.instalooter.proxy
```

**Comment by MatGamedu56** [comment]
I have the same error but me but I've been here a few days
"instalooter.cli[13362] CRITICAL "name=u'csrftoken', domain=None, path=None"
