### ISSUE TITLE
Error when user is authenticated

### ISSUE THREAD

**Issue by lormayna** [althonos/InstaLooter#233]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.3.2
```

## Environment

*Describe here your environment, including:*

* *OS*
Debian Buster 
* *Python version*
Python 3.6.5
* *`setuptools` version if reporting an issue with installation*
* *non-standard Python implementation if any*
Tried inside a virtualenv

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

(instadownloader) l@stelvio:~/project/instadownloader$ instalooter user test_private -u XXXX -p PPPP --traceback
2019-01-13 11:21:47 stelvio instalooter.cli[1374] CRITICAL
Traceback (most recent call last):
  File "/home/l/project/instadowloader/lib/python3.6/site-packages/instalooter/cli/__init__.py", line 151, in main
    login(args)
  File "/home/l/project/instadowloader/lib/python3.6/site-packages/instalooter/cli/login.py", line 21, in login
    InstaLooter._login(username, password)
  File "/home/l/project/instadowloader/lib/python3.6/site-packages/instalooter/looters.py", line 143, in _login
    token = next(c.value for c in login.cookies if c.name == 'csrftoken')
StopIteration
2019-01-13 11:21:47 stelvio instalooter.cli[1374] WARNING unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('XXX.XXX.XXX.XXX', 55858), raddr=('31.13.86.174', 443)>

**Comment by kolen** [comment]
Might be related to new "login security" functionality on Instagram. After `instalooter login` I'm getting "confirm that it's you" dialog on Instagram pages.

![image](https://user-images.githubusercontent.com/24191/51420093-7600ec00-1ba0-11e9-9318-de325dd247e1.png)

Also in mobile app:

![photo_2019-01-19_04-13-48](https://user-images.githubusercontent.com/24191/51420135-c8daa380-1ba0-11e9-8ef1-01cf786328a0.jpg)

So, seems like Zuck had added more DRM preventing you from getting data from their walled garden. Or they are doing the right way fighting account stealing, which is the real problem, as Instagram is tasty for spammers and scammers.

**Comment by althonos** [comment]
This should not occur in the next release: `InstaLooter` will now attempt to use the user-agent of your default browser.

**Comment by justingiffard** [comment]
@althonos, any progress on this bug? still getting blocked by Instagram authentication:

`ERROR: Login error: check your connection` when I try from bash

`ERROR: Login error: check your connection
unclosed <socket.socket fd=1120, family-AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto-0, laddr-('MY LOCAL IP', 52113), raddr-('MY EXTERNAL IP', 443)> ` when I try from command prompt

And then I get a "We Detected An Unusual Login Attempt" security warning as above on my phone

**Comment by mhkarimi** [comment]
@justingiffard same problem

**Comment by dausruddin** [comment]
I'm having the same problem

**Comment by dausruddin** [comment]
Turned out Instagram block my IP. I cannot login via browser.

**Comment by jeesnjohney** [comment]
Did any one resolve this issue ?

**Comment by dausruddin** [comment]
@jeesnjohney yes, I did. I used another server instead because Instagram blocked my server. Since it only have 1 IP address, I cannot change it.

**Comment by gnu-like** [comment]
My isp's ip changed but couldn't connect instalooter,although I confirmed the ip that's me in login activity of instagram.`instalooter v2.4.4`
