### ISSUE TITLE
fake_useragent directory and path?

### ISSUE THREAD

**Issue by marcvisconte** [althonos/InstaLooter#250]
I installed InstaLooter today (6/19/2019) via pip.

I tried running it from an admin-level CMD, it threw the errors noted below.
While trying to locate/troubleshoot, I found an additional directory created under {user}\AppData\Local, and a file installed:

C:\Users\{user}\AppData\Local\ **Martin Larralde** \instalooter\Cache\2.3.4\fake_useragent_0.1.11.json

I understand the purpose of the file, but not the choice of location.

Note:  I will also try running IL from Python as code: 
python "C:\Users\(user)\AppData\Roaming\Python\Python36\site-packages\instalooter\__main__.py"

## Library version

It does not say.  I just installed it today (6/14/2019)

```
C:\Users\{user}\AppData\Roaming\Python\Python36\Scripts>instalooter --version
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\Scripts\instalooter.exe\__main__.py", line 5, in <module>
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\cli\__init__.py", line 27, in <module>
    from ..looters import InstaLooter, HashtagLooter, ProfileLooter, PostLooter
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\looters.py", line 29, in <module>
    from .pages import ProfileIterator, HashtagIterator
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\pages.py", line 174
    return cls(data['id', session, "")
                                     ^
SyntaxError: invalid syntax
```

## Environment

*  Windows 7 Prof
*  Python 3.6.4

## Error description - installation
N/A

### Reproducible test case

*Are you using the CLI ?*
Yes

*If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*
```
C:\Users\_{user}_\AppData\Roaming\Python\Python36\Scripts>instaLooter user ian.luebbers "F:\misc_refile\Ian Leubbers\IGram" -u _{my Instagram ID}_
```

### Expected behaviour

It should download the pictures/videos on this profile.  This is a public portion, and I have verified that the content is accessible from a browser, even if I am not logged in.

### Actual behaviour

C:\Users\{user}\AppData\Roaming\Python\Python36\Scripts>instaLooter user ian.luebbers "F:\mdv_misc_refile\Family\Ian Leubbers\IGram" -u ma.rc2994
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\Scripts\instalooter.exe\__main__.py", line 5, in <module>
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\cli\__init__.py", line 27, in <module>
    from ..looters import InstaLooter, HashtagLooter, ProfileLooter, PostLooter
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\looters.py", line 29, in <module>
    from .pages import ProfileIterator, HashtagIterator
  File "C:\Users\{user}\AppData\Roaming\Python\Python36\site-packages\instalooter\pages.py", line 174
    return cls(data['id', session, "")
                                     ^
SyntaxError: invalid syntax

**Comment by althonos** [comment]
@marcvisconte: concerning the location of the file, it is installed in the [`appdirs`](https://pypi.org/project/appdirs/) userdata directory, which defaults to `C:\\Users\\{user}\\AppData\\Local\\{appauthor}\\{appname}`.

Concerning the `SyntaxError`, it seems your setup went wrong, because the line that is reported as failing is not to be found anywhere in the library: it seems the scripts got corrupted during installation.

**Comment by marcvisconte** [comment]
Thank you Martin.  It just surprised me to see person-named directories in my directory path.  I will attempt to install and use Instalooter again.

**Comment by althonos** [comment]
I used the `instalooter.__author__` variable, which has my full name in it, that's why :)
