### ISSUE TITLE
CRITICAL 'rhx_gis'

### ISSUE THREAD

**Issue by mrgloom** [althonos/InstaLooter#252]
```
instaLooter user benzogang_tape data/images/benzogang_tape --traceback
2019-06-20 02:57:44 MacBook-Pro.local instalooter.cli[37294] CRITICAL 'rhx_gis'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instalooter/cli/__init__.py", line 146, in main
    extended_dump=args['--extended-dump']
  File "/usr/local/lib/python3.6/site-packages/instalooter/looters.py", line 693, in __init__
    super(ProfileLooter, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/instalooter/looters.py", line 280, in __init__
    self.rhx = get_shared_data(res.text)['rhx_gis']
KeyError: 'rhx_gis'
```

```
python --version
Python 3.6.5

pip freeze | grep instalooter
instalooter==2.3.4
```

**Comment by mrgloom** [comment]
Looks related
https://github.com/althonos/InstaLooter/issues/247

**Comment by althonos** [comment]
Duplicate of #247.
