### ISSUE TITLE
[Bug] Cutoff by IG?

### ISSUE THREAD

**Issue by Ihatetotank** [althonos/InstaLooter#27]
After an excellent script to mass download got run, I started getting code errors. Is there a limit to IG connections?

Edit: That was an awful issue submittal. Allow me to elaborate:

I ran this as a script. It parses a .txt file and passes the line items to the instaLooter python script:
```
#!/bin/bash
a="$(wc -l < /mnt/md0/list.txt)"
((a++))
# echo "$a"
counter=1
while [ $counter -le $a ]
do
	STR="$(head -$counter /mnt/md0/list.txt | tail -1)"
	python -m instaLooter $STR "/mnt/md0/"$STR -v -N -c username:password
	((counter++))

done

```
Works great for the first few, then starts throwing connection errors:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/__main__.py", line 122, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/__main__.py", line 96, in main
    looter.login(login, password)
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 178, in login
    raise SystemError("Login error: check your connection")
SystemError: Login error: check your connection
```

**Comment by Ihatetotank** [comment]
Possibly due to too many concurrent logins?

**Comment by althonos** [comment]
Yes, this is an issue that happens when you don't get a 200 return code when you try to log out. It may be that Instagram kicks you out, but it may also be that there is a captcha at some point (?) that can't be filled automagically.

If you try to download pictures and medias from a public profile, you don't need to enter your credentials, so if you can refrain from using `-c` at every run :)

**Comment by Ihatetotank** [comment]
I can program in a private check for sure. So am I just stuck this way, or is there some way to undo the login error?

**Comment by Ihatetotank** [comment]
Boom. Private check, Success check, Error check. Now if I could just get rid of this stupid login error, I'd be done! Maybe if I had done this from the start I wouldn't be in the predicament I am now
```
#!/bin/bash

#pull list and count the lines to pass to loop
a="$(wc -l < /mnt/md0/list.txt)"
((a++))

counter=1
while [ $counter -le $a ]
do
	#Set username to rip as string
	STR="$(head -$counter /mnt/md0/list.txt | tail -1)"
	echo "Now ripping: "$STR
	
	# This runs the script and outputs the result to ./output
	python -m instaLooter "$STR" "/mnt/md0/"$STR -v -N 2>&1 | tee output
	#Checks the result in ./output and sets a variable based on it
	RESULT="$(grep -oh '100%\|No new\|SUCCESS' output)"
	#Check for Private
	PRIVATE="$(grep -oh 'private' output)"
	echo $PRIVATE
	
	if [ "$PRIVATE" = "private" ]; then
		#This is where I would call the login script if it worked
		#python -m instaLooter "$STR" "/mnt/md0/"$STR -N -v -c username:password
		((counter++))
		RESULT='SUCCESS'
	fi

#Check the Output file. If it contains any of the 'successful' outputs, advance. Or close
	if grep -q 	'oading\|No new\|SUCCESS' output; then
		echo "OK"
		((counter++))
	
	else
		counter=9001
		Echo "ERROR"
	fi

done
```

**Comment by Ihatetotank** [comment]
Is there any way around the return code error? I still get the Traceback error after multiple logins. I'm considering creating another instagram service account just for ripping, but it would be pointless if the login part of the python script breaks due to failed logout. Plus, if IG has some sort of catch for multiple logins and slays me with a captcha or whatever broke my credentials.

Side note, it appears the login error is only effecting the scrape attempt. I can login via browser just fine. I'm going to test the scrape on another Linux box and see if it's isolated to my IP address.

**Comment by Ihatetotank** [comment]
Also, not sure if this should be a separate feature request, but when ripping multiple IGs, it would be much easier to just login once, get the ripping done for all accounts, and log back out. That would totally fix this

**Comment by Ihatetotank** [comment]
Woo! Sorry for all the posts, but just trying to keep this ticket informed. I setup another text linux VM and the login (-c) worked correctly! There must be a way to fix my primary rip machine! There just has to be something stuck in the login script. Maybe a token that is saved or something?

**Comment by Ihatetotank** [comment]
Happened again, and a simple uninstall didn't fix it this time. :( 

Back to Error on login

**Comment by althonos** [comment]
Okay, so let's try the following Python script (experimental, but will prevent from login *n* times):
```python
#!/usr/bin/env python3
"""
no-ig-relogin.py:
	Download with InstaLooter without relogging for every user.

Usage:
	python no-ig-relogin.py <output_dir> <user_list>

Positional Arguments:
	output_dir		the directory where images are downloaded
					(in subdirectories named after each user)
	user_list		the path to the file containing the usernames
					from which to download pictures (one username
					per line).
"""

import instaLooter
import os
import sys
import getpass

if len(sys.argv) < 3:
	print("Usage:")
	print("   python no-ig-relogin.py <output_dir> <user_list>")
	sys.exit(1)
else:
	output_dir = sys.argv[1]
	user_list = sys.argv[2]

with open(user_list) as users_file:
	usernames = [l.strip() for l in users_file]

# Just give instaLooter the first profile so that it
# understands it needs to download pictures from a
# profile page.
looter = instaLooter.InstaLooter(profile=usernames[0], get_videos=True)

# Login asking for username and password from
# the command line, you can change this if you
# want to.
username = input("Username: ")
password = getpass.getpass()
looter.login(username, password)

for username in usernames:

	# Monkey patch the new target profile
	# and the new directory
	looter.target = username
	looter.directory = os.path.join(output_dir, username)

	# Create the directory if it does not exist
	if not os.path.isdir(looter.directory):
		os.makedirs(looter.directory)

	# Download new files only, with the progress bar
	looter.download(new_only=True, with_pbar=True)

```

**Comment by Ihatetotank** [comment]
So close! the usage command called is:
`python no-ig-relogin.py /mnt/md0/rips/ /mnt/md0/list.txt`

Output is as follows:

```
Username: myusername
Traceback (most recent call last):
  File "no-ig-relogin.py", line 41, in <module>
    username = input("Username: ")
  File "<string>", line 1, in <module>
NameError: name 'myusername' is not defined
```

Could this be because we're using the same username variable to login as we are to target?

**Comment by althonos** [comment]
Nope, this is because you run this script in Python2 although it is 
Python3 intended ;)
Just use Python 3 or replace input with raw_input for it to work with 
Python 2 ;)

**Comment by Ihatetotank** [comment]
True enough! Installed python3, reinstalled instaLooter via pip3, ran it with python3 with the command:
`python3 no-ig-relogin.py /mnt/md0/rips/ /mnt/md0/list.txt`

```
Username: myusername
Password:
Traceback (most recent call last):
  File "no-ig-relogin.py", line 43, in <module>
    looter.login(username, password)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/core.py", line 182, in login
    raise ValueError('Login error: check your login data')
ValueError: Login error: check your login data
```
Looks like the same login error I had before, just without the fancy colors. Original instaLooter still works on my test VM, so something is just stuck with this install and crapping out my login.

**Comment by Ihatetotank** [comment]
Started out great and then went to hell.

```
administrator@ubuntu:~$ sudo python3 no-ig-relogin.py ./rips/ ./list.txt                 
Username: myusername
Password:
Loading pages | 37%(  3 of 8)|####         |Elapsed Time: 0:00:00 |ETA: 0:00:01E         xception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new         _conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in          create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in          create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in          urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in          _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 787, in          _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 217, in conn         ect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new         _conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urll         ib3.connection.VerifiedHTTPSConnection object at 0x7fc6447f14e0>: Failed to esta         blish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in          urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in incr         ement
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ww         w.instagram.com', port=443): Max retries exceeded with url: /p/BKnqxqPBAQm/ (Cau         sed by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSCo         nnection object at 0x7fc6447f14e0>: Failed to establish a new connection: [Errno          101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/worker.py", line 46,          in run
    self._download_video(media)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/worker.py", line 98,          in _download_video
    with contextlib.closing(self.session.get(url)) as res:
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in reque         st
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com         ', port=443): Max retries exceeded with url: /p/BKnqxqPBAQm/ (Caused by NewConne         ctionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object          at 0x7fc6447f14e0>: Failed to establish a new connection: [Errno 101] Network i         s unreachable',))

Downloading |N/A%(0 of N/A)|             |Elapsed Time: 0:00:00 |ETA:  --:--:--T         raceback (most recent call last):
  File "no-ig-relogin.py", line 57, in <module>
    looter.download(new_only=True, with_pbar=True)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/core.py", line 395, i         n download
    self._join_workers(with_pbar=with_pbar)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/core.py", line 486, i         n _join_workers
    self._pbar.update(self.dl_count)
  File "/usr/local/lib/python3.5/dist-packages/progressbar/bar.py", line 501, in          update
    % (self.min_value, self.max_value))
ValueError: Value out of range, should be between 0 and 84
Downloading |100%(0 of N/A)|#            |Elapsed Time: 0:00:01 |ETA:  --:--:--
```

**Comment by Ihatetotank** [comment]
Still errors out for some reason.
```
administrator@ubuntu:~$ sudo python3 no-ig-relogin.py ./rips/ ./list.txt
Username: myusername
Password:
Loading pages |N/A%(0 of N/A)|                    |Elapsed Time: 0:00:00 |ETA:  --:--:--/usr/local/lib/python3.5/dist-packages/instaLooter/core.py:391: UserWarning: No new medias found.
  warnings.warn("No {}medias found.".format('new ' if new_only else ''))
Downloading |N/A%(0 of N/A)|                      |Elapsed Time: 0:00:00 |ETA:  --:--:--Traceback (most recent call last):
  File "no-ig-relogin.py", line 57, in <module>
    looter.download(new_only=True, with_pbar=True)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/core.py", line 395, in download
    self._join_workers(with_pbar=with_pbar)
  File "/usr/local/lib/python3.5/dist-packages/instaLooter/core.py", line 486, in _join_workers
    self._pbar.update(self.dl_count)
  File "/usr/local/lib/python3.5/dist-packages/progressbar/bar.py", line 501, in update
    % (self.min_value, self.max_value))
ValueError: Value out of range, should be between 0 and 35
Downloading |100%(0 of N/A)|#                     |Elapsed Time: 0:00:00 |ETA:  --:--:--

```

**Comment by althonos** [comment]
Try setting the with_pbar option to False in the looter.download 
parameters to hide the errors caused by instaLooter. Also, that would be 
great if you could give me a list of users similar to yours that raises 
errors on your side so that I could debug it more easily.

**Comment by nagualcode** [comment]
I am facing similar issues when running instaLooter hashtag -c login:pass sequentially in my script.
Could we preserve the cookie ?

**Comment by althonos** [comment]
@nagualcode: See the script I posted the 26th of January, it will allow you downloading from several profiles without reloging each time.

**Comment by nagualcode** [comment]
Hello, I am playing with that script... what if I want to give a 30min break and download new files?

**Comment by althonos** [comment]
You could make an infinite loop, and wait 30 minutes before checking usernames again:
```python
import instaLooter
import os
import sys
import getpass
import time

# ... blah blah blah ... #

username = input("Username: ")
password = getpass.getpass()
looter.login(username, password)

while True:
    for username in usernames:
        # ... same as before ... #
    time.sleep(30*60)    # Wait for 30mn
```

Such a script would run in foreground, so you'd have to spawn it through a Daemon, or just leave it running, but yeah it would check for new pictures every 30mn without relogging in between (I'm not sure how long the cookie would last, though).

**Comment by nagualcode** [comment]
Ok, thank you very much, I will give it a try

**Comment by IHTFY** [comment]
The ban lasts about 3 days. Using althonos' code above, avoiding rapid re-logins avoids this. I think the cookie lasts for an hour, but it might just be my bad hotel internet connection.

**Comment by althonos** [comment]
Closed, support for multiple account monitoring / downloading will be added in #17.
