### ISSUE TITLE
Login error, break on  'csrftoken'

### ISSUE THREAD

**Issue by yanchao7511461** [althonos/InstaLooter#287]
Traceback (most recent call last):
  File "/Users/yc/miniconda2/envs/instalooter/lib/python3.8/site-packages/instalooter/cli/__init__.py", line 151, in main
    login(args)
  File "/Users/yc/miniconda2/envs/instalooter/lib/python3.8/site-packages/instalooter/cli/login.py", line 21, in login
    InstaLooter._login(username, password)
  File "/Users/yc/miniconda2/envs/instalooter/lib/python3.8/site-packages/instalooter/looters.py", line 151, in _login
    token = next(c.value for c in login.cookies if c.name == 'csrftoken')
StopIteration
2020-05-17 19:48:26 ycdeMacBook-Air.lan instalooter.cli[9680] WARNING unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.123.150', 54188), raddr=('31.13.70.174', 443)>

**Comment by AdelMadkour** [comment]
I dont know how to fix this but all I know it originates from the 400 HTTP response when requesting the login url : https://www.instagram.com/accounts/login/ajax

**Comment by AdelMadkour** [comment]
I found a quick fix I have seen in another instagram repo ( a php one):

In file InstaLooter/instalooter/looters.py:
change this line :
	data = {'username': username, 'password': password}
to this line:
	data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}

And off course you need to add: 
import time 
on top of the looters.py file

**Comment by gnu-like** [comment]
> I found a quick fix I have seen in another instagram repo ( a php one):
> 
> In file InstaLooter/instalooter/looters.py:
> change this line :
> data = {'username': username, 'password': password}
> to this line:
> data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}

Solved;thanks

**Comment by yanchao7511461** [comment]
> I found a quick fix I have seen in another instagram repo ( a php one):
> 
> In file InstaLooter/instalooter/looters.py:
> change this line :
> data = {'username': username, 'password': password}
> to this line:
> data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}

thanks, it works .
