### ISSUE TITLE
Runtime errors when using the latest version of tenacity (version 6.2.0)

### ISSUE THREAD

**Issue by dmp1ce** [althonos/InstaLooter#288]
## Library version

2.4.2 installed on Arch Linux through the AUR: https://aur.archlinux.org/packages/instalooter

## Environment

* Arch Linux
* Python 3.8.3

## Error description - runtime

At runtime I get the following errors:

```
$ instalooter --version
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tenacity 6.2.0 (/usr/lib/python3.8/site-packages), Requirement.parse('tenacity~=5.0'), {'instalooter'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/instalooter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3253, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tenacity~=5.0' distribution was not found and is required by instalooter
```

I think Arch Linux has a newer version of tenacity. I expected instalooter to work with the latest python libraries.

**Comment by althonos** [comment]
I updated the required `tenacity` version in `v2.4.3`, this should not happen anymore.
