### ISSUE TITLE
v2.4.2 user not fount for all accounts

### ISSUE THREAD

**Issue by evanrich** [althonos/InstaLooter#289]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.4.2
```

## Environment

*Describe here your environment, including:*

Ubuntu 18.04 LTS
Python 3.6.9

## Error description - installation

I managed to get this working for a bit after creating the user-agent.txt file in the cache folder, but suddenly now it gives "user not found" for any account I throw at it.  It works fine for hashtags, but using  "user" stopped working:

```
instalooter user elliekimxo ./elliekimxo/ -v -N -T {username}.{datetime} --traceback
2020-06-05 21:29:08 homelab-a instalooter.cli[19096] NOTICE Starting download of `elliekimxo`
2020-06-05 21:29:08 homelab-a instalooter.cli[19096] CRITICAL user not found: 'elliekimxo'
Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.6/site-packages/instalooter/cli/__init__.py", line 173, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "/home/evan/.local/lib/python3.6/site-packages/instalooter/looters.py", line 450, in download
    pages_iterator = self.pages()   # type: Iterable[Dict[Text, Any]]
  File "/home/evan/.local/lib/python3.6/site-packages/instalooter/looters.py", line 723, in pages
    it = ProfileIterator.from_username(self._username, self.session)
  File "/home/evan/.local/lib/python3.6/site-packages/instalooter/pages.py", line 178, in from_username
    raise ValueError("user not found: '{}'".format(username))
ValueError: user not found: 'elliekimxo'
evan@homelab-a:/nfs/instagramrips$

```

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

```
instalooter user elliekimxo ./elliekimxo/ -v -N -T {username}.{datetime} --traceback
```

### Expected behaviour

It's supposed to work

### Actual behaviour

It suddenly stopped working with user, only works with hashtag

**Comment by Niggggggo** [comment]
+1 I have the same issue

**Comment by brndnsvr** [comment]
+1 me too

**Comment by starf1337** [comment]
Hopefully the author can update it soon. Although if anyone can find an in-code fix... That would be nice too. I have tried igScraper and it sort of **suuuks**.

**Comment by sfc-gh-lrobles** [comment]
> strange... I added a
> 
> ```
> print(user_data['entry_data']) 
> ```
> 
> below the user_data =... line, and now it works, although it's sptting out tons of data from user_data...
> 
> edit: removed the print line (commented it out) and now it seems to work still.

tried this as well but no luck

comes back with
```
{u'LoginAndSignupPage': [{u'captcha': {u'enabled': False, u'key': u''}, u'gdpr_required': False, u'username_hint': u'', u'tos_version': u'row'}]}
```

**Comment by starf1337** [comment]
Had it working again but I broke something and kept poor notes. Just conjecture but it seems to be having a problem with cookie session data and captcha. Could just be that my personal login has expired but even if that is the case I cannot logout or login anymore.

To anyone who happens across this, @evanrich has the right idea using print(). At the very least, it shows what data is being passed byref and/or byval in problem areas. Good thinking.

**Comment by evanrich** [comment]
@starf1337  i can't even get login to work, but im also not using it on a gui based system, so maybe thats why... it seems it can't do a headless chrome login.   Also another oddity is that sometimes it complains that a user doesn't exist when you can clearly find that user in instagram, and their profile isn't hidden...
  The author seems to have abandoned this?  My python is rudimentary, but when I have the time I'll try this on a gui based system using some print statements to debug whats going on

**Comment by starf1337** [comment]
Ok so I looked around a bit and it looks like the other major instagram projects are having the same issue. 

(i.e. https://github.com/postaddictme/instagram-php-scraper/issues/636)

I'll periodically keep an eye on these projects as one of them is bound to figure this thing out. Even if it is in another language at least we will be able to define the problem.

**Comment by starf1337** [comment]
Hey @evanrich somebody found a fix on another ticket.

" AdelMadkour commented on May 18 •

I found a quick fix I have seen in another instagram repo ( a php one):

In file InstaLooter/instalooter/looters.py:
change this line :
data = {'username': username, 'password': password}
to this line:
data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}"

It worked for me.

**Comment by sfc-gh-lrobles** [comment]
Worked for me a few times and now its erroring again on "user not found"
```
        session = cls._init_session(session)
        headers = copy.deepcopy(session.headers)
        homepage = "https://www.instagram.com/"
        login_url = "https://www.instagram.com/accounts/login/ajax/"
        data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}
```

**Comment by Niggggggo** [comment]
> 
> 
> Hey @evanrich somebody found a fix on another ticket.
> 
> " AdelMadkour commented on May 18 •
> 
> I found a quick fix I have seen in another instagram repo ( a php one):
> 
> In file InstaLooter/instalooter/looters.py:
> change this line :
> data = {'username': username, 'password': password}
> to this line:
> data = {'username': username, 'enc_password': '#PWD_INSTAGRAM_BROWSER:0:' + str(time.time()) + ':' + password}"
> 
> It worked for me.

I tried using this but unfortunately that didn't work for me.

Funnily enough instalooter works fine without any problems when I run it from my computer at home (or in a Linux VM), but causes the issue above as soon as it runs from my server.

Maybe this has something to do with Insta blocking specific IP addresses?

**Comment by evanrich** [comment]
I'm not sure @Niggggggo I run from a server at home and sometimes it works, sometimes it doesnt... like I just started running it now on a list, it grabbed the first 3 and now every single user is "not found"

**Comment by evanrich** [comment]
FYIW,still occurs in 2.4.3

**Comment by NotRogu** [comment]
Any update?

**Comment by crdpa** [comment]
Same issue here. I think instagram is temporarily blocking ips that are scrapping data.

**Comment by evanrich** [comment]
i dont think they're blocking ips, as I can browse on my desktop/phone.  But the second instalooter runs, even now with 2.4.4, user not found, even on my own profile.   They might be analyzing how scrapes happen, or maybe they've updated their api or something and instalooter doesn't work right anymore.

**Comment by C4l1b3r** [comment]
I had to login for this to download all images.

**Comment by keithstrydom** [comment]
It's rate limiting of unauthenticated logins.

**Comment by C4l1b3r** [comment]
I run this on Android non root and it works off and on.

**Comment by sridharmani0510** [comment]
same prob here
couldnt find  a fix

**Comment by xTaromarux** [comment]
Clearing the instalooter cache this is the answer 
delete cache.txt and user-agent.txt
(~/.cache/instalooter/2.4.4    on Linux
C:\Users\YOUR-USERNAME\AppData\Local\Martin Larralde\instalooter\Cache\2.4.4     on Windows ). 
It helps ~(https://github.com/althonos/InstaLooter/issues/322#issuecomment-791234354)

**Comment by artlung** [comment]
I am having this issue with `instalooter user <USER>` commands. Trying to make sure I am authenticated right but not sure I am.

`instalooter logout` gives me back `Cookie file not found.`

`instalooter login` prompts me to login. Tried with both email and username. Tried with 2FA on and off, all result in errors but mobile instagram does let me know I was logging in with Mac OS X. With username: ` Login error: check your login data` and with email ` 'NoneType' object has no attribute 'group`

Would like to try @xTaromarux suggestion to delete instalooter cache. Where is that on MacOS? (`11.6.2` if it matters)

instalooter version `2.4.4`

**Comment by xTaromarux** [comment]
@artlung
First try download cookie from Firefox.
https://instaloader.github.io/troubleshooting.html
maybe that's why instaloader can't find them because they don't exist

and to login you have to use this command 
`instaloader --login USER_NAME`
because instaloader is for account login and instalooter is for downloading content

about file path cookie I can't help you because I don't have macOS. 
So you have to find by yourself.

**Comment by artlung** [comment]
I was able to uninstall and reinstall instalooter to get around the problem. instaloader does not look related to me. Thanks @xTaromarux

**Comment by choxner** [comment]
It worked for me once I used `instalooter login`

Make sure to turn off two step on whatever account you log in as!

**Comment by Gyombie** [comment]
Hi, I've been trying all the solutions above but I get the error "user not found" for any accounts I try. Has there been any progress on a solution for this issue ??
