### ISSUE TITLE
Installation failed with: ImportError: 'module' object has no attribute 'check_specifier'

### ISSUE THREAD

**Issue by Rohlik** [althonos/InstaLooter#291]
## Environment

*Describe here your environment, including:*

* *OS*
Red Hat Enterprise Linux Server 7.8
* *Python version*
Python 2.7.5
* *`setuptools` version if reporting an issue with installation*
setuptools                       36.2.7
* *pip version*
pip                              20.1.1

## Error description - installation

During installation via pip (`pip install --user instalooter --pre`) I received this error:
```
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YdSo9H/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YdSo9H/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-GWRmm4                   
         cwd: /tmp/pip-install-YdSo9H/future/                                                                                                                                                                     
    Complete output (17 lines):                                                                                                                                                                                   
    Traceback (most recent call last):                                                                                                                                                                            
      File "<string>", line 1, in <module>                                                                                                                                                                        
      File "/tmp/pip-install-YdSo9H/future/setup.py", line 180, in <module>                                                                                                                                       
        **setup_kwds                                                                                                                                                                                              
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup                                                                                                                                           
        _setup_distribution = dist = klass(attrs)                                                                                                                                                                 
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__                                                                                                                           
        _Distribution.__init__(self,attrs)                                                                                                                                                                        
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__                                                                                                                                        
        self.finalize_options()                                                                                                                                                                                   
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options                                                                                                                   
        ep.load()(self, ep.name, value)                                                                                                                                                                           
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load                                                                                                                       
        return self.resolve()                                                                                                                                                                                     
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2326, in resolve                                                                                                                    
        raise ImportError(str(exc))                                                                                                                                                                               
    ImportError: 'module' object has no attribute 'check_specifier'                                                                                                                                               
    ----------------------------------------                                                                                                                                                                      
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by althonos** [comment]
Actually, try updating your `setuptools` version, I think this is probably the main issue here.

**Comment by Rohlik** [comment]
Thank you, it works now with `future v0.16`.
