### ISSUE TITLE
Error if {username} in template

### ISSUE THREAD

**Issue by berkutx** [althonos/InstaLooter#294]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter 2.4.4
```

## Environment

*Describe here your environment, including:*

* *Debian*
* *Python 3.6*

## Error description - runtime
If i add {username} in template i got error. If not - all is OK.
OK: 

> instalooter hashtag test temp -n 10 --jobs 4 -T {datetime}.{width}.{height}.{id} 

ERROR: 

> instalooter hashtag test temp -n 10 --jobs 4 -T {username}.

> 
2020-08-05 16:53:00 nsfw-parser instalooter.cli[8437] NOTICE Starting download of `test`
0it [00:00, ?it/s]                                                                                                                                  2020-08-05 16:53:02 nsfw-parser instalooter.cli[8437] CRITICAL 'PostPage'                                              | 0/45099683 [00:00<?, ?it/s]
2020-08-05 16:53:02 nsfw-parser instalooter.cli[8437] NOTICE Terminating 4 remaining workers...
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instalooter/cli/__init__.py", line 173, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "/usr/local/lib/python3.6/dist-packages/instalooter/looters.py", line 473, in download
    new_only, condition)
  File "/usr/local/lib/python3.6/dist-packages/instalooter/looters.py", line 622, in _fill_media_queue
    media = self.get_post_info(media['shortcode'])
  File "/usr/local/lib/python3.6/dist-packages/instalooter/looters.py", line 352, in get_post_info
    if 'graphql' in data['entry_data']['PostPage'][0]:
KeyError: 'PostPage'

**Comment by althonos** [comment]
I cannot reproduce on ArchLinux with Python 3.8 currently.

**Comment by pi43r** [comment]
Same issue with username on windows:

```
instalooter.cli[20856] CRITICAL 'PostPage'                         | 0/912328 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ms\AppData\Roaming\Python\Python37\site-packages\instalooter\cli\__init__.py", line 173, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "C:\Users\ms\AppData\Roaming\Python\Python37\site-packages\instalooter\looters.py", line 471, in download
    new_only, condition)
  File "C:\Users\ms\AppData\Roaming\Python\Python37\site-packages\instalooter\looters.py", line 620, in _fill_media_queue
    media = self.get_post_info(media['shortcode'])
  File "C:\Users\ms\AppData\Roaming\Python\Python37\site-packages\instalooter\looters.py", line 350, in get_post_info
    if 'graphql' in data['entry_data']['PostPage'][0]:
KeyError: 'PostPage'
```

works fine with other arguments
