### ISSUE TITLE
Script hangs on error

### ISSUE THREAD

**Issue by Bangaio64** [althonos/InstaLooter#30]
Python 3.6.0 on Windows 7 x64

If the profile name doesn't exist, I get the following error and then the scripts hangs. I have to kill python.exe from the Task Manager.

```
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 229, in pages
    media_info = data['entry_data'][self._page_name][0][self._section_name]['media']
KeyError: 'ProfilePage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\instaLooter.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\__main__.py", line 113, in main
    new_only=args['--new'],
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 388, in download
    new_only=new_only)
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 437, in _fill_media_queue
    for media in self.medias(media_count=media_count, with_pbar=with_pbar, timeframe=timeframe):
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 286, in _timeless_medias
    for page in self.pages(media_count=media_count, with_pbar=with_pbar):
  File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 231, in pages
    warnings.warn("Could not find page of user: {}".format(self.target), stacklevel=1)
  File "c:\program files (x86)\python36-32\lib\warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
TypeError: warn_with_hues() takes from 4 to 5 positional arguments but 6 were given
```

Same issue happens if it's a private profile and credentials aren't entered, and if the time option is given and there's no new pictures to download.

Not sure if this is a problem on my end since I don't have much experience with python. I did try it from an elevated command prompt just in case and the same thing occured.

**Comment by althonos** [comment]
The issue happened because the doc I used stated the wrong signature of the custom formatting function for the `warnings` module, this was fixed in 8984ed35806e6520cc44b944f2b17dc7a84039fc.
