### ISSUE TITLE
downloads fail with CRITICAL 'PostPage'

### ISSUE THREAD

**Issue by LazyBoot** [althonos/InstaLooter#309]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.4.4
```

## Environment

*Describe here your environment, including:*

* windows 10
* Python 3.7.9

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

```
instalooter user purplemuffinz purplemuffinz -v --traceback
```

### Expected behaviour

*What's supposed to happen ? *
downloads completes

### Actual behaviour

```020-11-20 17:06:17 LazyBoot instalooter.cli[14620] CRITICAL 'PostPage'
Traceback (most recent call last):
  File "d:\source\repos\instalooter\.env\lib\site-packages\instalooter\cli\__init__.py", line 173, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "d:\source\repos\instalooter\.env\lib\site-packages\instalooter\looters.py", line 471, in download
    new_only, condition)
  File "d:\source\repos\instalooter\.env\lib\site-packages\instalooter\looters.py", line 620, in _fill_media_queue
    media = self.get_post_info(media['shortcode'])
  File "d:\source\repos\instalooter\.env\lib\site-packages\instalooter\looters.py", line 350, in get_post_info
    if 'graphql' in data['entry_data']['PostPage'][0]:
KeyError: 'PostPage'```

**Comment by bialyrycerz** [comment]
Same issue on Mac with 2.4.4_1, macos 10.15.7.

**Comment by jhein05** [comment]
Same here. Mac 10.14.6, Python 3.8.6

**Comment by bjente** [comment]
Same here. Mac 10.13.6. Instalooter 2.4.4. Python 3.7.3

And the weird thing is, this morning it did work with complete url's. All of a sudden it stopped working and now I keep on getting this critical postpage error.

**Comment by AkiselNipese** [comment]
Same on linux fedora 31, python 3.7.9, instalooter 2.4.4

**Comment by SsJVasto** [comment]
Same on linux Debian Buster, python 3.7.3
Same on linux Raspbian, python 3.7.3

**Comment by AkiselNipese** [comment]
Here's my story (fedora 31, python 3.7.9, instalooter 2.4.4, i'm login BTW): 
i launched a script (just a dozen calls to `instalooter post`) to download multiple post at once all worked.
Next i tried to download `instalooter user` and failed in the middle.
Same error as OP
anything i tried was same error
my account was blocked for some reason, i had to retrieve it through codes from email and phone.
same error trying to download anything.
`instalooter logout` ; `instalooter login`
worked. Not sure why.

**Comment by richieadler** [comment]
Same error in Windows 7, instalooter 2.4.4, python 3.8.5

**Comment by max-arnold** [comment]
```
 /Users/user/.virtualenvs/instagram-story/lib/python3.7/site-packages/instalooter/looters.py(351)get_post_info()                                                           | 1/5534 [00:09<13:51:56,  9.02s/it]
    350             import ipdb; ipdb.set_trace()
--> 351             if 'graphql' in data['entry_data']['PostPage'][0]:
    352                 return data['entry_data']['PostPage'][0]['graphql']['shortcode_media']

ipdb> data['entry_data']
{'LoginAndSignupPage': [{'captcha': {'enabled': False, 'key': ''}, 'gdpr_required': False, 'tos_version': 'row', 'username_hint': ''}]}
```

**Comment by aalliikk** [comment]
> ```
>  /Users/user/.virtualenvs/instagram-story/lib/python3.7/site-packages/instalooter/looters.py(351)get_post_info()                                                           | 1/5534 [00:09<13:51:56,  9.02s/it]
>     350             import ipdb; ipdb.set_trace()
> --> 351             if 'graphql' in data['entry_data']['PostPage'][0]:
>     352                 return data['entry_data']['PostPage'][0]['graphql']['shortcode_media']
> 
> ipdb> data['entry_data']
> {'LoginAndSignupPage': [{'captcha': {'enabled': False, 'key': ''}, 'gdpr_required': False, 'tos_version': 'row', 'username_hint': ''}]}
> ```
> 
> `instalooter login` did help.

Please, what does it mean `instalooter login` did help?

**Comment by max-arnold** [comment]
> Please, what does it mean `instalooter login` did help?

It means that you need to run the `instalooter login` command and enter your instagram login details

**Comment by jhein05** [comment]
> > Please, what does it mean `instalooter login` did help?
> 
> It means that you need to run the `instalooter login` command and enter your instagram login details

YES, fixed the problem here too.

**Comment by jhein05** [comment]
> > Please, what does it mean `instalooter login` did help?
> 
> It means that you need to run the `instalooter login` command and enter your instagram login details

Be careful, though, your account might get blacklisted.

**Comment by ibex-are-goats** [comment]
> Be careful, though, your account might get blacklisted.

By logging into instagram? Or by downloading pictures? Who says you'll get blacklisted for that?

**Comment by 89z** [comment]
Same error
