### ISSUE TITLE
KeyError: 'PostPage'

### ISSUE THREAD

**Issue by cmoztas** [althonos/InstaLooter#311]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.4.4
```

## Environment

*Describe here your environment, including:*

* *Windows 10 x64 Pro*
* *Python 3.9.0*

## Error description

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "C:\Users\cmozt\Desktop\InstaTracker\main.py", line 81, in download_all_post
  File "instalooter\looters.py", line 370, in download_pictures
  File "instalooter\looters.py", line 469, in download
  File "instalooter\looters.py", line 620, in _fill_media_queue
  File "instalooter\looters.py", line 350, in get_post_info
KeyError: 'PostPage'

### Expected behaviour

Profillooter fails. At first I thought it was due to punctuation, but I get the same error with all usernames I try while using API.

As a matter of fact, I have not used the program I wrote in about 1 month. But with the same codes, I used my program with your API for 5 months.

Now I don't understand what's wrong. If it's due to my lack of Python or any other reason, please don't be sorry.

**Comment by edusachs** [comment]
Same problem here.

**Comment by rakemen** [comment]
Same issue for me.

**Comment by crdpa** [comment]
Same here. Or getting user not found.

**Comment by aalliikk** [comment]
Same problem here. It seems to be this `thing` is not properly working anymore. I fixed more errors along the way right before the beginning of the installation, and now the experience is getting more like `instaLooser`. 

`youtube-dl` can't download Instagram TV videos as well, please, prove that I am wrong!

**Comment by dekiesel** [comment]
Same here:

```
from instalooter.looters import PostLooter
code= 'CLt6RG7pfqk'
looter= PostLooter(code)
d_media = looter.get_post_info(code)
```

yields 

```Exception has occurred: KeyError
'PostPage'
  File "/home/john/python-code/webAPI/social_media/supermetrics/qa/instaloot.py", line 4, in <module>
    d_media = looter.get_post_info(code)
```

**Comment by robml** [comment]
Same here
