### ISSUE TITLE
 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by palumbo** [althonos/InstaLooter#349]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter 2.4.4
```

## Environment

*Describe here your environment, including:*

MacOS Monterrey v12.1
Python 3.3.9

## Error description - installation

*If you have an issue with installation, make sure you use a recent `setuptools` version
before filing a bug ! If the error is still there, describe the command you used to
install, and make sure you reported your environment in details. In particular,
if you encounter a critical error with the CLI, please post the program output when
running with the `--traceback` flag.*

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

```
instalooter post https://www.instagram.com/p/CX8LSDwsVNP/?utm_source=ig_web_copy_link -v -T {username}.{id}
```

### Expected behaviour

Instalooter downloads post to the current directory

### Actual behaviour

Receive 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/cli/__init__.py", line 167, in main
    n = looter.download(
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/looters.py", line 858, in download
    medias_queued = self._fill_media_queue(
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/looters.py", line 616, in _fill_media_queue
    for media in six.moves.filter(_condition, medias_iter):
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/looters.py", line 824, in medias
    info = self.info
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/looters.py", line 792, in info
    self._info = self.get_post_info(self.code)
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/looters.py", line 349, in get_post_info
    data = get_shared_data(res.text)
  File "/opt/homebrew/Cellar/instalooter/2.4.4_2/libexec/lib/python3.10/site-packages/instalooter/_utils.py", line 94, in get_shared_data
    return json.loads(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> instagram CX8LSDwsVNP
GET https://www.instagram.com/p/CX8LSDwsVNP/?__a=1
GET https://scontent-dfw5-1.cdninstagram.com/v/t51.2885-15/e35/269956920_347341633494589_3527950430869939008_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com&_nc_cat=1&_nc_ohc=Rwgijqxyh9YAX8rnGG2&edm=AABBvjUBAAAA&ccb=7-4&ig_cache_key=MjczNzExMjI5MzAzNDc3NTM3NQ%3D%3D.2-ccb7-4&oh=00_AT-0bT-JvGEJVwzCEvs2NpZxxCu46bZh8tesbZ6Xdka34g&oe=61D028DA&_nc_sid=83d603
~~~

https://github.com/89z/mech

**Comment by AdamJMilton** [comment]
I am having the same issue. I tried logging out, logging in, and rebooting. No joy.

Instalooter 2.4.4
Raspbian version 10/buster 
Python version 3.7.3.
