### ISSUE TITLE
Exception has occurred: AttributeError 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by samuelbraun04** [althonos/InstaLooter#360]
**PROBLEM DETAILS:**

I'm getting the following error (full traceback lower in issue):

```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'group'
```

at the commented line in my code:

```
from instalooter.looters import ProfileLooter
looter = ProfileLooter("dreamwifetheband") #error at this line
looter.download('C:/Users/samlb/Downloads/memeFiles', media_count=5)
```

**MY VERSION:**

My version of instalooter is 2.4.4 and I'm running it on Python 3.9.13

**FULL TRACEBACK:**

```
Traceback (most recent call last):
  File "c:\Users\samlb\Documents\MEME_VIDEOS\makeMemeVideos.py", line 9, in <module>
    looter = ProfileLooter("dreamwifetheband")
  File "C:\Users\samlb\AppData\Roaming\Python\Python39\site-packages\instalooter\looters.py", line 705, in __init__        
    super(ProfileLooter, self).__init__(**kwargs)
  File "C:\Users\samlb\AppData\Roaming\Python\Python39\site-packages\instalooter\looters.py", line 287, in __init__        
    token = get_shared_data(res.text)['config']['csrf_token']
  File "C:\Users\samlb\AppData\Roaming\Python\Python39\site-packages\instalooter\_utils.py", line 94, in get_shared_data   
    return json.loads(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Crisez0694** [comment]
same error that i got

**Comment by JoeGarcia2** [comment]
Same with me

**Comment by WilliamNT** [comment]
Same here

**Comment by BrandonMiller18** [comment]
Same here. Did anyone find a solution to this?

**Comment by jjaaccoobb** [comment]
+1

**Comment by haiderkhalid** [comment]
+1

**Comment by atcapollo** [comment]
+1

**Comment by extralarge** [comment]
+1

**Comment by mohammadhoseinGhezelsofla** [comment]
Hello. According to my research, Instagram no longer shows user information on the html page. For example, if we used to go to the link https://www.instagram.com/'username' the user data was available on the html page. But recently it is no longer the case.
According to my research, they have transferred such information to another part, which was not very easy for me to obtain, considering that if we send wrong information to the Instagram site, it will ban us for 24 hours.

**Comment by evdmolen** [comment]
I have the same problem. I think that instagram updated the api and the instalooter is not updated anymore.

**Comment by skmachine** [comment]
Any chance instalooter starts working? I am using https://rapidapi.com/neotank/api/instagram130/ now to extract profile information from their /account-info endpoint and it works fine and returns account JSON with latest 12 posts, without requiring any cookies or login information, but it is a paid api.

**Comment by kebigbo** [comment]
> Any chance instalooter starts working? I am using https://rapidapi.com/neotank/api/instagram130/ now to extract profile information from their /account-info endpoint and it works fine and returns account JSON with latest 12 posts, without requiring any cookies or login information, but it is a paid api.

How did you implement and replace instalooter with rapidapi?
