### ISSUE TITLE
random crash: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by dannyvoid** [althonos/InstaLooter#48]
This issue happens randomly with Windows; on different profiles. Doesn't happen at all with my linux install.

`Loading pages |100%(87 of 87)|##################################################################################|Elapsed Time: 0:01:47 |ETA:  0:00:00
Traceback (most recent call last):

  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals

  File "C:\Python27\Scripts\instaLooter.exe\__main__.py", line 9, in <module>

  File "c:\python27\lib\site-packages\instaLooter\cli.py", line 130, in main
    new_only=args['--new'],

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 388, in download
    new_only=new_only)

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 451, in _fill_media_queue
    medias_queued, stop = self._add_media_to_queue(media, condition, media_count, medias_queued, new_only)

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 462, in _add_media_to_queue
    media_basename = self._make_filename(media)

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 503, in _make_filename
    media = self.get_post_info(media['code'])

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 431, in get_post_info
    media = self._get_shared_data(res)['entry_data']['PostPage'][0]['media']

  File "c:\python27\lib\site-packages\instaLooter\core.py", line 445, in _get_shared_data
    return json.loads(self._RX_SHARED_DATA.match(script.text).group(1))

AttributeError: 'NoneType' object has no attribute 'text'
`

**Comment by althonos** [comment]
I thought at first this was a regex issue, but it seems to occur earlier than that: BeautifulSoup doesn't seem to be able to find the <script/> part of the page, which is weird.

If possible, could you try updating on your windows machine, and maybe install `lxml` ? I'll performance tests on my windows as well.

**Comment by althonos** [comment]
I actually got that with Python 2 only, when tests are ran on Travis they sometimes fail because of this. I have no idea why, since relaunching the build always fixes the issue.

So:
* either the `re` module has a bug in Python 2 (the regex does not extract the right metadata from the page)
* or the `request` module has a bug in Python 2 (the page is not successfully fetched)

**Comment by althonos** [comment]
UPDATE: encountered the bug today on Travis-CI in a Python 3.5 worker (see log at https://travis-ci.org/althonos/InstaLooter/jobs/229790053). So the issue is not version specific. I would lean towards a network issue.
