### ISSUE TITLE
Got mistake since yesterday.

### ISSUE THREAD

**Issue by lelechen63** [althonos/InstaLooter#50]
It can not work since yesterday night and I tried three accounts, all got same error, hope you can update it.The error message is shown as bellow:

15:41:55 - SUCCESS - Logged in.
Loading pages |N/A%(0 of 4167)|                                                                                                                |Elapsed Time: 0:00:00 |ETA:  --:--:--Traceback (most recent call last):
  File "/Users/channelcryster/anaconda/bin/instaLooter", line 11, in <module>
    sys.exit(main())
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/cli.py", line 137, in main
    new_only=args['--new'],
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/core.py", line 401, in download
    new_only=new_only
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/core.py", line 468, in _fill_media_queue
    medias_queued, stop = self._add_media_to_queue(media, condition, media_count, medias_queued, new_only)
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/core.py", line 479, in _add_media_to_queue
    media_basename = self._make_filename(media)
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/core.py", line 520, in _make_filename
    media = self.get_post_info(media['code'])
  File "/Users/channelcryster/anaconda/lib/python2.7/site-packages/instaLooter/core.py", line 448, in get_post_info
    media = self._get_shared_data(res)['entry_data']['PostPage'][0]['media']
KeyError: u'media'

**Comment by althonos** [comment]
I can reproduce that, IG must have changed something with their API. I'll investigate. Thanks for report !

**Comment by lelechen63** [comment]
Thanks! Hope you can tell me when it's fixed, we have a project rely on your awesome tool!

**Comment by althonos** [comment]
Tests seem to work back again, new release (v0.8.1) available on GitHub and PyPI.

For the technical stuff, Instagram just added a nesting level in their post page content (likely to be able to add multiple posts in a list, although I don't really know why) and renamed the `'media'` attribute to `'graphql'/'shortcode_media'`.
