### ISSUE TITLE
 Hang with UnicodeDecodeError

### ISSUE THREAD

**Issue by artasoftware** [althonos/InstaLooter#55]
Hi. Tried to download some photos and this is what I get:

/usr/local/bin/instaLooter instagram_profile Images/downloaded/inst/
Loading pages |N/A%(0 of 43)|                                                         |Elapsed Time: 0:00:00 |ETA:  --:--:--Traceback (most recent call last):
  File "/usr/local/bin/instaLooter", line 11, in <module>
    load_entry_point('instaLooter==0.8.2', 'console_scripts', 'instaLooter')()
  File "/home/korben/.local/lib/python2.7/site-packages/instaLooter/cli.py", line 137, in main
    new_only=args['--new'],
  File "/home/korben/.local/lib/python2.7/site-packages/instaLooter/core.py", line 401, in download
    new_only=new_only
  File "/home/korben/.local/lib/python2.7/site-packages/instaLooter/core.py", line 472, in _fill_media_queue
    medias_queued, stop = self._add_media_to_queue(media, condition, media_count, medias_queued, new_only)
  File "/home/korben/.local/lib/python2.7/site-packages/instaLooter/core.py", line 484, in _add_media_to_queue
    if not os.path.exists(os.path.join(self.directory, media_basename)):
  File "/usr/lib/python2.7/posixpath.py", line 78, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

Any suggestions?

**Comment by althonos** [comment]
Could you give me a profile where this error occurs, as well as the version of the program ?

**Comment by kabotage** [comment]
Hey, I have the same error. Happens all the time on profiles with multiple photos inside one(1) post. eg. "nasa". Woking now flawlessly on the latest version. Thanks!

"Loading pages |N/A%(0 of 210)|              |Elapsed Time: 0:00:00 |ETA:  --:--:--Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/__main__.py", line 2, in <module>
    main()
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/cli.py", line 137, in main
    new_only=args['--new'],
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/core.py", line 401, in download
    new_only=new_only
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/core.py", line 468, in _fill_media_queue
    medias_queued, stop = self._add_media_to_queue(media, condition, media_count, medias_queued, new_only)
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/core.py", line 477, in _add_media_to_queue
    media, condition, media_count, medias_queued, new_only)
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/core.py", line 492, in _add_sidecars_to_queue
    media = self.get_post_info(media['code'])
  File "/home/kabotage/Documents/github/InstaLooter/instaLooter/core.py", line 448, in get_post_info
    media = self._get_shared_data(res)['entry_data']['PostPage'][0]['media']
KeyError: 'media'
^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt"

**Comment by artasoftware** [comment]
@althonos it happens with any account. version is the last one == 0.8.2.

**Comment by althonos** [comment]
@artasoftware have you tried with latest instaLooter version (`0.9.3`) ?
@kabotage : this was not the same error, yours refer to #50 actually (which was fixed).

**Comment by artasoftware** [comment]
@althonos yes it worked. First it was an error "ERROR - 'ascii' codec can't decode byte 0xd0 in position 13: ordinal not in range(128)" but after I've used location only with english letters, it worked. Thanks!

**Comment by althonos** [comment]
Well, non-ascii characters should work, so I'm keeping this issue open until I find a way to prevent this error (not a priority though).
