### ISSUE TITLE
[Bug] Cannot identify image file error

### ISSUE THREAD

**Issue by MohamedIM** [althonos/InstaLooter#64]
An exception is thrown wile executing this command:
```instaLooter -v -m instagram```
```python
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/instaLooter/worker.py", line 47, in run
    self._download_photo(media)
  File "/usr/lib/python3.6/site-packages/instaLooter/worker.py", line 98, in _download_photo
    self._add_metadata(photo_name, media)
  File "/usr/lib/python3.6/site-packages/instaLooter/worker.py", line 68, in _add_metadata
    img = PIL.Image.open(path)
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/user/Pictures/1510248326967369727.jpg'
```
Using version 0.9.6

**Comment by althonos** [comment]
Hi, I cannot reproduce that error on Linux with version 0.9.6 as well, could you give me your `Pillow` / `PIL` version as well ?

**Comment by MohamedIM** [comment]
Using ```PIL``` version: ```4.1.1-1```

**Comment by MohamedIM** [comment]
It seems that it's a permission issue when I tried to debug I found that image file is not actually an image it's an HTML file saying you don't have permission to access this image on this server:
```html
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;ig&#45;s&#45;c&#45;a&#46;akamaihd&#46;net&#47;18443717&#95;182420295616102&#95;6509180678351880192&#95;n&#46;jpg" on this server.<P>
Reference&#32;&#35;18&#46;3c0fdd58&#46;1494974074&#46;4490338
</BODY>
</HTML>
```
