### ISSUE TITLE
TypeError: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by Baemir** [althonos/InstaLooter#75]
I'm getting this traceback when I try to run instaLooter on Python 3.7:

```
Traceback (most recent call last):
  File "/usr/bin/instaLooter", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/instaLooter/utils.py", line 94, in new_func
    result = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/instaLooter/cli.py", line 119, in main
    argv_positional = [param for param in argv if not param.startswith("-")]
TypeError: 'NoneType' object is not iterable
```

Not sure if I'm doing something wrong on my end or the script broke somehow.

**Comment by althonos** [comment]
Thanks, I was able to reproduce it with the following command:
`instaLooter instagram /tmp/instagram -v`.

Actually I had just forgotten that I changed the default value of the `argv` kwarg in the main function. Now it should work fine.
