### ISSUE TITLE
Weird warning & InstaLooter won't download all posts

### ISSUE THREAD

**Issue by aaasddd** [althonos/InstaLooter#98]
Noticed a few days ago that I sometimes get a warning saying instalooter could not find a page. 

` WARNING - Could not find page of user: justinbieber`

The warning comes similarly like when instaLooter checks for new posts and doesn't find any. This is what I run:
`instaLooter  justinbieber C:\Users\AZ\Desktop\Insta\JB--get-videos -T "{username}.{datetime}.{id}" -N -m`
Sometimes the message appears even when instalooter continues downloading.

I tried to download different profiles to test things around, and I noticed that instalooter didn't download all posts. For example, I ran:

`C:\Users\AZ\>instaLooter  alexiaelkaim D:\Backup\Pictures\Instagram\Profiles\alexiaelkaim --get-videos -T "{username}.{datetime}.{id}" -N -m` , downloading a profile with 1108 posts. Now, instagram website doesn't count the additional posts in multiposts, so it's a few more pictures than that (as instaLooter also downloads multiposts".) I look at my folder, and I have 1116 pictures. The catch is that a week ago I downloaded the same profile, and in that folder I have 1235. Maybe instagram changed something and not all posts are downloaded now? 

I also get another warning. I have gotten the same warning since I used instaLooter, but rarely. The posts did download properly so I didn't think of it at all, but now whenever I use instaLooter, the warning always pops up.

`C:\Users\AZ\>instaLooter alexiaelkaim D:\Backup\Pictures\Instagram\Profiles\alexiaelkaim --get-videos -T "{username}.{datetime}.{id}" -N -m 
Loading pages | 25%(12 of 47)|###           |Elapsed Time: 0:00:08 |ETA: 0:00:24Exception in thread Thread-15:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\site-packages\instaLooter\worker.py", line 65, in run
    self._download_video(media)
  File "c:\python27\lib\site-packages\instaLooter\worker.py", line 149, in _download_video
    self._dl(video_url, video_name)
  File "c:\python27\lib\site-packages\instaLooter\worker.py", line 158, in _dl
    with contextlib.closing(self.session.get(source)) as res:
  File "c:\python27\lib\site-packages\requests\sessions.py", line 515, in get
    return self.request('GET', url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 652, in send
    r.content
  File "c:\python27\lib\site-packages\requests\models.py", line 825, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "c:\python27\lib\site-packages\requests\models.py", line 750, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))
`

**Comment by althonos** [comment]
@aaasddd : is this still occuring ? To the look of your traceback, this seem to be a connection issue. Make sure you have the latest version of `requests`.

#100 may also fix this.

**Comment by edmoore-mq** [comment]
I'm getting this error on version 0.14.0. System is ubuntu with updated modules:

> alembic (0.9.9)
appdirs (1.4.3)
banal (0.3.3)
beautifulsoup4 (4.6.0)
bottle (0.12.13)
bs4 (0.0.1)
certifi (2018.1.18)
chardet (3.0.4)
coloredlogs (9.0)
dataset (1.0.6)
docopt (0.6.2)
enum34 (1.1.6)
fake-useragent (0.1.10)
fs (2.0.20)
futures (3.2.0)
hues (0.2.2)
humanfriendly (4.10)
idna (2.6)
instaLooter (0.14.0)
lxml (4.2.1)
Mako (1.0.7)
MarkupSafe (1.0)
monotonic (1.4)
normality (0.5.11)
pip (9.0.3)
praw (5.4.0)
prawcore (0.15.0)
progressbar2 (3.36.0)
psycopg2 (2.7.4)
pycrypto (2.6.1)
python-dateutil (2.7.2)
python-editor (1.0.3)
python-utils (2.3.0)
pytz (2018.3)
PyYAML (3.12)
requests (2.18.4)
setuptools (36.2.7)
six (1.11.0)
SQLAlchemy (1.2.6)
tenacity (4.9.0)
tqdm (4.19.9)
typing (3.6.4)
update-checker (0.16)
urllib3 (1.22)


> username@ubuntuBox:~/test1$ instaLooter instagram
07:06:12 - WARNING - Could not find page of user: instagram
07:06:12 - WARNING - No medias found.


> user@ubuntuBox:~/test1$ instaLooter instagram
07:08:56 - WARNING - Could not find page of user: instagram
07:08:56 - WARNING - No medias found.
